# NB : remember filter must stay before every other filter, else, we get this strange behaviour, 
# where header shows we are identified, and homepage does not display "add outing" due to cache
rememberFilter:
  class: rememberFilter
  
rendering: ~
web_debug: ~
security:  ~

# generally, you will want to insert your own filters here :
FiltersSwitchFilter:
  class: FiltersSwitchFilter
  
MyCacheFilter:
  class: MyCacheFilter
  param:
    condition: %SF_CACHE%
# MyCacheFilter replaces the original filter (hence disactivated) to enable action caching with user's culture :
cache:     ~
  enabled: false

common:    ~    

# commented until we find why it takes so long on somes requests to minify JS and CSS...
#sfCombineFilter:
#  class:   mysfCombineFilter
#  param:
#    javascripts:    true
#    stylesheets:    true
#    root_js_only:   false
#    root_css_only:  false

flash:     ~

# switch between regular and mobile version of the site
MobileFilter:
  class: MobileFilter

MyExecutionFilter:
  class: MyExecutionFilter
  param:
    type: execution
# MyExecutionFilter replaces the original filter (hence disactivated) to enable action caching with user's culture :
execution: ~
  enabled: false
