_filter_form:
  enabled: off 

_linked_huts:
  enabled: off

_huts_short_filter:
  enabled: off

_huts_filter:
  enabled: off

_feature:
  enabled: off 

filter:
  enabled: off 

popupSuccess:
  enabled: on
